# Generated by Django 4.1.7 on 2023-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_time', models.DateTimeField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='poets',
            name='posts',
        ),
        migrations.AddField(
            model_name='poets',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
