# Generated by Django 4.1.7 on 2023-04-01 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0002_post_remove_poets_posts_poets_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poet_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='dekhta.poets'),
        ),
        migrations.AlterField(
            model_name='post',
            name='d_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 0, 35, 32, 804360)),
        ),
    ]
