# Generated by Django 4.0.5 on 2023-04-02 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0003_post_poet_id_alter_post_d_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='d_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 8, 24, 39, 119627)),
        ),
    ]
