# Generated by Django 4.1.7 on 2023-04-18 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0005_poets_user_alter_post_d_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='d_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 3, 17, 28, 83329)),
        ),
    ]
