# Generated by Django 4.1.7 on 2023-04-18 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0006_alter_post_d_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poets',
            name='pfp',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='d_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 3, 24, 48, 571808)),
        ),
    ]
