# Generated by Django 4.1.7 on 2023-04-21 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0014_alter_post_d_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='d_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 9, 1, 28, 179132)),
        ),
    ]
