# Generated by Django 4.1.7 on 2023-05-06 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekhta', '0019_alter_post_d_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='d_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 24, 51, 866183)),
        ),
    ]
